sudo: required

services:
  - docker

language: csharp
solution: BeerMeCore.sln
mono: none
dotnet: 2.0.0
dist: trusty

before_script:
  - dotnet restore
  - npm install

script:
  - dotnet publish -c Release -o ./Publish

after_success:
  - docker build -t beermecore .
  - docker tag beermecore jpinc/beerme
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jpinc/beerme;
