# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: HbZcXoDDxnVGVXmnmEUeJw==
  DOCKER_PASS:
    secure: hnX1Ql2pk+d1spofSPIjceHvEGBNvz/pe/0GFcp0PqA=

# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3


# scripts that run after cloning repository
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node ''
  - node --version
  - npm --version

  # install modules
  - npm install
  - docker version

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: false                  # enable MSBuild parallel builds
  project: BeerMeCore.sln          # path to Visual Studio solution or project
  publish_wap: false               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: false         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: false  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  # MSBuild verbosity level
  verbosity: minimal

# scripts to run before build
before_build:
  - dotnet restore
  - npm install

# scripts to run after build
after_build:
  - dotnet publish -c Release -o ./Publish
  - docker build -t jpinc/beerme .

#---------------------------------#
#       tests configuration       #
#---------------------------------#

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  # pushing entire folder as a zip archive
  - path: Publish


#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy_script:
  - docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
  - docker push jpinc/beerme

#---------------------------------#
#         notifications           #
#---------------------------------#
